version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - '50051:50051'
    volumes:
      - ./proto:/proto
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672 # AMQP
      - 15672:15672 # UI
